FORMAT: 1A
HOST: https://api.albumparrot.com/

# Album Parrot API

The Album Parrot API is a freely available resource designed to 
allow access to all the resources in the Album Parrot eco-system.

## Albums [/designer/albums]

### List all albums

+ Response 200 (application/json)
        
        [
            {
            
            }
        ]

### Create a new album