FORMAT: 1A

# Album Parrot API

# Security [/authenticate]
Authenticating Users

Authentication is managed through JSON Web Tokens (JWT). Once you have a token, you should pass it in the Authentication HTTP header on all subsequent requests.
Tokens are single use, and you will get a new token returned to you as an Authentication header in the response.
You should use the new token on the next request, and so on.

## Fetch a security token [POST]
Authenticates the credentials passed, and returns a token for future requests if successful.

+ Request (application/json)
    + Body

            [
                {
                    "email": "me@design-studio.com",
                    "password": "P$a$$w0rd"
                }
            ]

+ Response 200 (application/json)
    + Body

            {
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2FwaS5kZXYuYWxidW1wYXJyb3QuY29tXC9hdXRoZW50aWNhdGUiLCJpYXQiOjE0NjExNzk5NjIsImV4cCI6MTQ2MTE4MzU2MiwibmJmIjoxNDYxMTc5OTYyLCJqdGkiOiJjNjhiMWRmOTM1ZjVmMmI5NjdhOGJjYjYwMDBjOGFhNSJ9.7de57BSaYwPJ9cFu4j1NsP6AXwNya_Ose2scho_tMEc"
            }

# Albums [/albums]
Album resource representation.

# Email Settings [/email/settings]

# Email Templates [/email/templates]

# Email Logs [/email/log]

# Albums [/designer/albums]
Album design resource representation.

## Get all albums [GET]
Get all the album designs associated with the current user.

+ Response 200 (application/json)
    + Body

            {
                "data": [
                    {
                        "id": "050b29e7-414f-4018-94c7-74c814c9c220",
                        "title": "voluptates porro sapiente"
                    },
                    {
                        "id": "07ce8d6d-d0b4-4aea-bff6-dc7bf559894c",
                        "title": "ea consequatur omnis"
                    }
                ]
            }

## Get a single album design [GET /designer/albums/{album}]
Get the specific album design

+ Parameters
    + album: `050b29e7-414f-4018-94c7-74c814c9c220` (string, required) - The id of the album to fetch

+ Response 200 (application/json)
    + Body

            {
                "data": {
                    "id": "050b29e7-414f-4018-94c7-74c814c9c220",
                    "title": "voluptates porro sapiente"
                }
            }

## Create an album design [POST]
Create a new album design

+ Request (application/json)
    + Body

            {
                "title": "Tuscany Wedding",
                "dimensions": {
                    "width": 7088,
                    "height": 3544,
                    "dpi": 300
                },
                "crop": {
                    "width": 7088,
                    "height": 3544
                }
            }

+ Response 201 (application/json)
    + Body

            {
                "data": {
                    "id": "99557b15-1cf4-45a3-ba1e-d34f9a7da9e2",
                    "title": "Tuscany Wedding",
                    "dimensions": {
                        "width": 7088,
                        "height": 3544,
                        "dpi": 300
                    },
                    "crop": {
                        "width": 7088,
                        "height": 3544
                    }
                }
            }

## Update an existing album design [PUT /designer/albums/{album}]
Update an existing album design

+ Parameters
    + album: `050b29e7-414f-4018-94c7-74c814c9c220` (string, required) - The id of the album to update

+ Request (application/json)
    + Body

            {
                "title": "Tuscany Wedding 2"
            }

+ Response 200 (application/json)
    + Body

            []

## Delete an album [DELETE /designer/albums/{album}]
Deleting the specified album will delete all related spreads.

+ Parameters
    + album: `050b29e7-414f-4018-94c7-74c814c9c220` (string, required) - The id of the album to delete

+ Response 200 (application/json)
    + Body

            []

# Spreads [/designer/albums/{album}/spreads]

## List all spreads [GET]
Get all the spreads associated with the specified album design.

+ Parameters
    + album: `album_3c543c5040ad4809ad39d1373f890cc8` (string, required) - The id of the album containing the spread

+ Response 200 (application/json)
    + Body

            {
                "data": [
                    {
                        "id": "spread_4f0a1f6477cb4d6cac716469238b408b",
                        "order": 0,
                        "areas": {
                            "data": []
                        }
                    },
                    {
                        "id": "spread_9377700fdab04a10a021fff0a29ebe59",
                        "order": 1,
                        "areas": {
                            "data": []
                        }
                    },
                    {
                        "id": "spread_71d12701c8ec4eb29f3a8578b03f8822",
                        "order": 2,
                        "areas": {
                            "data": []
                        }
                    }
                ]
            }

## Delete an spread [DELETE /designer/albums/{album}/spreads/{spread}]
Deleting the specified spread will delete all related areas.

+ Parameters
    + album: `050b29e7-414f-4018-94c7-74c814c9c220` (string, required) - The id of the album to delete
    + spread: `spread_04185c6f6618433eb9f045576bb8171b` (string, required) - The id of the spread to fetch

+ Response 200 (application/json)
    + Body

            []

# Templates [/designer/templates]
Album design templates representation.

## Fetch Templates [GET /designer/templates{?type,photosPerSpread}]
Get all the template applicable to the specified type of album design, and number of photos per spread.

This will return a series of templates containing references to the position and size of each photo area.
These should be interpreted as ratios to be applied against both the real size of the album canvas and the size of the album design
visually on the screen.

+ Parameters
    + type: `square` (string, optional) - The type of album design. Available options are square, vertical and horizontal
        + Default: square
    + photosPerSpread: `3` (number, optional) - The number of areas in the spread
        + Default: 1

+ Response 200 (application/json)
    + Body

            {
                "data": [
                    {
                        "areas": [
                            {
                                "top": 0,
                                "left": 0,
                                "order": 0,
                                "width": 0.333333333333,
                                "height": 1
                            },
                            {
                                "top": 0,
                                "left": 0.333333333333,
                                "order": 1,
                                "width": 0.333333333333,
                                "height": 1
                            },
                            {
                                "top": 0,
                                "left": 0.666666666667,
                                "order": 2,
                                "width": 0.333333333333,
                                "height": 1
                            }
                        ]
                    }
                ]
            }

# AppHooksEmailLogHook